#!/usr/bin/env bash

app_name="$(basename "${BASH_SOURCE[0]}")"

USAGE=$(expand -t 4 << EOF
Usage:
	$app_name
		Output root path of this Git repository.

Options:
	-?, --help
		Show this help information and exit.
EOF
)

while [[ $# -gt 0 ]]; do
	case "$1" in
		-\?|--help)
			echo "$USAGE"
			exit 0
			;;
		-*)
			echo "Unknown option: $1" >&2
			exit 1
			;;
		*)
			echo "Unexpected argument: $1" >&2
			exit 1
			;;
	esac
done

if [[ $(uname -s) == CYGWIN* ]]; then
	cygpath "$(git rev-parse --show-toplevel)"
else
	git rev-parse --show-toplevel
fi
