#!/usr/bin/env bash

app_name="$(basename "${BASH_SOURCE[0]}")"

USAGE=$(expand -t 4 << EOF
Usage:
	$app_name
		Returns 0 if current working directory is a Git repository, non-zero otherwise.

Options:
	-q, --quiet
		Suppress stderr output.

	-?, --help
		Show this help information and exit.
EOF
)

quiet=0

while [[ $# -gt 0 ]]; do
	case "$1" in
		-q|--quiet)
			quiet=1
			shift
			;;
		-\?|--help)
			echo "$USAGE"
			exit 0
			;;
		-*)
			echo "$app_name: [Error] Unknown option: $1" >&2
			exit 1
			;;
		*)
			echo "$app_name: [Error] Unexpected argument: $1" >&2
			exit 1
			;;
	esac
done

if [[ quiet -eq 0 ]]; then
	git rev-parse --git-dir > /dev/null
else
	git rev-parse --git-dir &> /dev/null
fi
