#!/usr/bin/env bash

app_name="$(basename "${BASH_SOURCE[0]}")"

print_help() {
	expand -t 4 << EOF
Usage:
	$app_name
		Output .git directory path of this Git repository.

Options:
	-?, --help
		Show this help information and exit.
EOF
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		-\?|--help)
			print_help
			exit 0
			;;
		-*)
			echo "$app_name: [Error] Unknown option: $1" >&2
			exit 1
			;;
		*)
			echo "$app_name: [Error] Unexpected argument: $1" >&2
			exit 1
			;;
	esac
done

if [[ $(uname -s) == CYGWIN* ]]; then
	git rev-parse --git-dir | cygpath -f -
else
	git rev-parse --git-dir
fi
